export const CHART_SETTINGS = {
    OUTER_RADIUS_BLUE: 90,
    OUTER_RADIUS_ORANGE: 83,
    INNER_RADIUS_GENERAL: 64,
    DATA_SET_NAME: 'primary',
    GREY_BACKGROUND_COLOR: 'rgba(238, 238, 242,1)',
};
